name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2 

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Adjust based on your Laravel version
        tools: 'composer'

    - name: Install PHP Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build Assets
      run: npm install && npm run build

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: "66.29.131.162"  # Using IP instead of hostname
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: "/home/assetsms/public_html/sms/"  # Target path on server
        local-dir: "./"  # Upload everything from local repo root
        protocol: "ftp"
        port: 21
        exclude: |
          **/.git*
          **/node_modules/**
          **/vendor/**
          **/tests/**
          **/storage/**
